#!/bin/bash
source ~/.config/statbar.conf

# Help Message
HELP_MSG="Display system info for usage with different status bars. \nUsage: statbar [arguments]\nArguments:\n\t--help - show this message\n\t--date - show current date (formated)\n\t--time - show current time (formated)\n\t--wireless - show wireless signal level\n\t--battery - show battery charge\n\t--cpu show cpu load\n\t--ram show memory load\n\t--networkrx - show network RX\n\t--networktx - show network TX"

# Execution
for arg in "$@"; do
  shift
  case "$arg" in
    '--help')
        echo -e $HELP_MSG
        ;;
    '--date')
        echo -e $DATE_COLOR$DATE_ICON $(date +"$DATE_FORMAT")
        ;;
    '--time')
        echo -e $TIME_COLOR$TIME_ICON $(date +"$TIME_FORMAT")
        ;;
    '--wireless')
        link_essid=$(iwconfig $WIRELESS_INTERFACE | grep -o -P '(?<=ESSID:).*')
        if [ "$link_essid" = "off/any  " ]; then
            echo -e $WIRELESS_COLOR$WIRELESS_NO_CONNECTION_ICON
        else
            link_quality=$(iwconfig $WIRELESS_INTERFACE | grep -o -P '(?<=Quality=).*(?= Signal)' | cut -d '/' -f 1)
            link_quality_max=$(iwconfig $WIRELESS_INTERFACE | grep -o -P '(?<=Quality=).*(?= Signal)' | cut -d '/' -f 2)
            link_percent=$(echo "scale=2 ; $link_quality / $link_quality_max * 100" | bc | rev | cut -c4- | rev)

            echo -e $WIRELESS_COLOR$WIRELESS_ICON $link_percent%
        fi
        ;;
    '--battery')
        battery_status=$(acpi | grep -o -P '(?<=: ).*(?=,.*%)')
        battery=$(acpi | grep -o -P '(?<=, ).*(?=%)')
        if [ "$battery_status" = "Discharging" ]; then
            echo -e $BATTERY_COLOR$BATTERY_DISCHARGE_ICON $battery%
	    if [ "$battery" -lt $BATTERY_DISCHARGE_THRESHOLD ]; then
		dunstify -i $BATTERY_LOW_ICON -h string:x-dunst-stack-tag:$BATTERY_WARNING_TAG -t $BATTERY_WARNING_TIMEOUT "$BATTERY_WARNING_TITLE" "$BATTERY_WARNING_TEXT"
	    fi
        else
            echo -e $BATTERY_COLOR$BATTERY_CHARGE_ICON $battery%
        fi
        ;;
    '--cpu') 
        cpu=$(top -bn1 | awk '/Cpu/ {print $2}' | rev | cut -c3- | rev)
        echo -e $CPU_COLOR$CPU_ICON $cpu%
        ;;
    '--ram')
        ram_available=$(cat /proc/meminfo | awk '/MemAvailable/ {print $2}')
        ram_total=$(cat /proc/meminfo | awk '/MemTotal/ {print $2}')
        ram_percent=$(echo "scale=2 ; 100 - ($ram_available / $ram_total * 100)" | bc | rev | cut -c4- | rev)
        echo -e $RAM_COLOR$RAM_ICON $ram_percent%
        ;;
    '--networkrx')
        rx=$(ifstat -t 1 | awk "/$WIRELESS_INTERFACE/ {print $6}")
        echo -e $NETWORK_RX_COLOR$NETWORK_RX_ICON $rx
        ;;
    '--networktx')     
        tx=$(ifstat -t 1 | awk "/$WIRELESS_INTERFACE/ {print $8}")
        echo -e $NETWORK_RX_COLOR$NETWORK_RX_ICON $tx
        ;;
    *)
        echo -e $HELP_MSG
        ;;
  esac
done
